INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (1, 2, 'Điện Thoại');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (2, 2, 'Máy Tính Bảng');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (3, 2, 'Pin sạc dự phòng');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (4, 2, 'Ốp lưng & Bao da điện thoại');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (5, 2, 'Phụ Kiện');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (6, 2, 'Tivi');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (7, 2, 'Tai Nghe');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (8, 2, 'Máy Nghe Nhạc');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (9, 2, 'Loa');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (10, 2, 'Laptop');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (11, 2, 'Linh kiện máy tính');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (12, 1, 'Quần Áo');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (13, 1, 'Túi Xách');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (14, 1, 'Kính Thời Trang');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (15, 1, 'Giày Dép');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (16, 1, 'Đồng Hồ');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (17, 1, 'Trang Sức');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (18, 3, 'Đồ Gia Dụng');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (19, 3, 'Dụng Cụ Làm Bếp');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (20, 3, 'Đồ nội Thất');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (21, 3, 'Đồ Trang Trí');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (22, 4, 'Đồ trang điểm');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (23, 4, 'Nước Hoa');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (24, 4, 'Chăm sóc da mặt');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (25, 4, 'Dụng cụ y tế');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (26, 5, 'Đồ Thể thao nam');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (27, 5, 'Đồ Thể thao nữ');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (28, 5, 'Phụ kiện thể thao');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (29, 5, 'Phụ kiện du lịch');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (30, 6, 'Quần áo trẻ sơ sinh');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (31, 6, 'Đồ chơi giáo dục trẻ em');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (32, 6, 'Đồ dùng bú sữa & Ăn dặm');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (33, 6, 'Máy bay và đồ chơi điều khiển từ xa');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (882676011, 6, 'Mo Hinh Lap Ghep');
INSERT INTO `category` (`category_id`, `category_father`, `category_name`) VALUES (884375917, 2, 'Ohayo');
